services:
  client:
    container_name: client
    image: client
    build:
      context: ./client
      dockerfile: client.dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - server
  server:
    container_name: server
    image: server
    build:
      context: ./server
      dockerfile: server.dockerfile
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?schema=public
  db:
    container_name: db
    image: postgres:16.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}